sudo: required
language: generic

services:
  - docker

# cache:
#   directories:
#     - $HOME/google-cloud-sdk

# env:
#   global:
#     - CLOUDSDK_CORE_DISABLE_PROMPTS=1
#     - SHA=$(git rev-parse HEAD)

before_install:
  # - openssl aes-256-cbc -K $encrypted_248412cf5212_key -iv $encrypted_248412cf5212_iv -in service-account.json.enc -out service-account.json -d
  # - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  #   rm -rf $HOME/google-cloud-sdk;
  #   curl https://sdk.cloud.google.com | bash > /dev/null;
  #   fi
  # - source $HOME/google-cloud-sdk/path.bash.inc
  # - gcloud components update kubectl
  # - gcloud version
  # - gcloud auth activate-service-account --key-file service-account.json
  # - gcloud config set project k2multi-212923
  # - gcloud config set compute/zone us-central1-a
  # - gcloud container clusters get-credentials k2cluster
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fuzzythread/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fuzzythread/react-test npm test
  - echo tests pass

# after_success:
#   - docker build -t fuzzythread/multi-client ./client
#   - docker build -t fuzzythread/multi-nginx ./nginx
#   - docker build -t fuzzythread/multi-server ./server
#   - docker build -t fuzzythread/multi-worker ./worker
#   # Log in to the docker CLI
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   # Take those images and push them to docker hub
#   - docker push fuzzythread/multi-client
#   - docker push fuzzythread/multi-nginx
#   - docker push fuzzythread/multi-server
#   - docker push fuzzythread/multi-worker

# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   on:
#    branch: master